// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID     *string `json:"_id"`
	Title  *string `json:"title"`
	Author *string `json:"author"`
}

type Mustation struct {
	AddBook   *Book   `json:"addBook"`
	AddReview *Review `json:"addReview"`
}

type NewBook struct {
	Title  *string `json:"title"`
	Author *string `json:"author"`
}

type NewReview struct {
	Bookid    *int    `json:"bookid"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
	Score     *int    `json:"score"`
	Text      *string `json:"text"`
}

type Review struct {
	ID        *string `json:"_id"`
	Bookid    *int    `json:"bookid"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
	Score     *int    `json:"score"`
	Text      *string `json:"text"`
	Created   *string `json:"created"`
}
